--UC-1:
CREATE DATABASE ADDRESS_Book

--UC-2:
CREATE TABLE ADDRESS_BOOK(
ID INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
FIRST_NAME VARCHAR(25) NOT NULL,
LAST_NAME VARCHAR(25) NOT NULL,
ADDRESS VARCHAR(100) NOT NULL,
CITY VARCHAR(25) NOT NULL,
STATE VARCHAR(25) NOT NULL,
ZIP_CODE FLOAT NOT NULL,
PHONE_NUMBER FLOAT NOT NULL,
EMAIL VARCHAR(50) NOT NULL)

SELECT * FROM ADDRESS_BOOK


--UC-3:
INSERT INTO ADDRESS_BOOK VALUES('Harini','Lekkala','11A','Vizag','Visakhapatnam',654321,9087654321,'harini.lekkala1997@gmail.com')
INSERT INTO ADDRESS_BOOK VALUES('Harshini','Potnuri','12B','Madhurwada','Vsp',645321,8907654321,'harshini.potnuri1997@gmail.com')
INSERT INTO ADDRESS_BOOK VALUES('Pardhavi','Neeli','13C','Rajasthan','Jaipur',634521,7890123456,'pardhavi.neeli@gmail.com')
INSERT INTO ADDRESS_BOOK VALUES('Ojaswi','Chukkala','14C','Vsp','Andhra',634521,7890123456,'ojaswi.chukkala@gmail.com')
INSERT INTO ADDRESS_BOOK VALUES('Vennila','Bandaru','15C','Visakhapatnam','AndhraPradesh',634521,7890123456,'vennila.bandaru@gmail.com')

DELETE  FROM ADDRESS_BOOK Where ID = '4'
DELETE  FROM ADDRESS_BOOK Where ID = '5'
DELETE  FROM ADDRESS_BOOK Where ID = '6'


SELECT * FROM ADDRESS_BOOK

--UC-4:
Update  ADDRESS_BOOK Set City = 'Podugupalem' where FIRST_NAME = 'Harini'

SELECT * FROM ADDRESS_BOOK

--UC-5:
Delete From ADDRESS_BOOK Where LAST_NAME = 'Chukkala'

SELECT * FROM ADDRESS_BOOK

--UC-6: Retriving the data from Address Book
SELECT * FROM ADDRESS_BOOK WHERE CITY = 'Podugupalem'
SELECT * FROM ADDRESS_BOOK WHERE STATE = 'Vsp'


--UC7:
SELECT CITY, COUNT(CITY) AS CITY_COUNT FROM ADDRESS_BOOK GROUP BY CITY
SELECT STATE, COUNT(STATE) AS STATE_COUNT FROM ADDRESS_BOOK GROUP BY STATE

--UC-8:
SELECT * FROM ADDRESS_BOOK where CITY = 'Visakhapatnam'  ORDER BY FIRST_NAME, LAST_NAME 
SELECT * FROM ADDRESS_BOOK

--UC-9:
ALTER TABLE ADDRESS_BOOK ADD TYPE VARCHAR(20) NOT NULL DEFAULT('')
UPDATE ADDRESS_BOOK SET TYPE = 'FAMILY' WHERE FIRST_NAME = 'Harini'
UPDATE ADDRESS_BOOK SET TYPE = 'FRIENDS' WHERE FIRST_NAME = 'Harshini'
UPDATE ADDRESS_BOOK SET TYPE = 'PROFESSION' WHERE FIRST_NAME = 'Pardhavi'
UPDATE ADDRESS_BOOK SET TYPE = 'FRIENDS' WHERE FIRST_NAME = 'Vennila'

SELECT * FROM ADDRESS_BOOK

--UC-10:
SELECT TYPE, COUNT(TYPE) AS TYPE_COUNT FROM ADDRESS_BOOK GROUP BY TYPE

--UC-11
INSERT INTO ADDRESS_BOOK VALUES('Pravalika','Raj','20Z','Penduti','Rajastan',612345,6543217890,'pravalika@gmail.com','Friends')
INSERT INTO ADDRESS_BOOK VALUES('Pravalika','Raj','20Z','Penduti','Rajastan',612345,6543217890,'pravalika@gmail.com','Family')

SELECT * FROM ADDRESS_BOOK

--UC-12

CREATE TABLE CONTACT_DETAILS(
CONTACT_ID INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
FIRSE_NAME VARCHAR(25) NOT NULL,
LAST_NAME VARCHAR(25) NOT NULL,
ADDRESS VARCHAR(50) NOT NULL,
CITY VARCHAR(20),
STATE VARCHAR(20),
PIN INT NOT NULL,
EMAIL VARCHAR(25),
)

SELECT * FROM CONTACT_DETAILS

INSERT INTO CONTACT_DETAILS (FIRSE_NAME,LAST_NAME,ADDRESS,CITY,STATE,PIN,EMAIL) VALUES ('HARINI','LEKKALA','NO 1 - COIMBATORE','COIMBATORE','TAMILNADU',656598,'harini@gmail.com')
INSERT INTO CONTACT_DETAILS VALUES ('HARSHINI','POTNURI','NO 2, ELA ADDRESS','SALEM','TAMILNADU',654512,'harshini@gmail.com')
INSERT INTO CONTACT_DETAILS VALUES ('PRIYA','REDDY','NO 3, PRIYA ADDRESS','PALAKKAD','KERALA',565626,'priya@gmail.com')
INSERT INTO CONTACT_DETAILS VALUES ('OJASWI','CHUKLA','NO 4,  ADDRESS','BANGALORE','KARNATAKA',564423,'ojaswi@gmail.com')
INSERT INTO CONTACT_DETAILS VALUES ('SAI','CHUKLA','NO 5, RAVI ADDRESS','COIMBATORE','TAMILNADU',658696,'sai@gmail.com')
INSERT INTO CONTACT_DETAILS VALUES ('kishore','lekkala','NO 4, SENTHIL ADDRESS','COIMBATORE','TAMILNADU',632145,'kishore@gmail.com')


CREATE TABLE CONTACT_TYPES(
CONTACT_ID INT NOT NULL,
CONTACT_GROUP VARCHAR(20) NOT NULL,
)
SELECT * FROM CONTACT_TYPES

INSERT INTO CONTACT_TYPES VALUES (1,'FAMILY')
INSERT INTO CONTACT_TYPES VALUES (1,'FRIEND')
INSERT INTO CONTACT_TYPES VALUES (2,'FRIEND')
INSERT INTO CONTACT_TYPES VALUES (3,'FAMILY')
INSERT INTO CONTACT_TYPES VALUES (4,'FRIEND')
INSERT INTO CONTACT_TYPES VALUES (5,'FAMILY')
INSERT INTO CONTACT_TYPES VALUES (6,'FRIEND')

CREATE TABLE PHONE_NUMBER(
CONTACT_ID INT NOT NULL,
PRIMARY_NUMBER FLOAT NOT NULL,
SECONDARY_NUMBER FLOAT,
)
SELECT * FROM PHONE_NUMBER

INSERT INTO PHONE_NUMBER VALUES (1,9876543210,9876543210)
INSERT INTO PHONE_NUMBER VALUES (2,7894561230, NULL)
INSERT INTO PHONE_NUMBER VALUES (3,8527419630,9876543210)
INSERT INTO PHONE_NUMBER VALUES (4,9632584176, NULL)
INSERT INTO PHONE_NUMBER VALUES (5,7532149562, NULL)
INSERT INTO PHONE_NUMBER VALUES (6,6589423563,9876543210)

--UC-13
SELECT * FROM CONTACT_DETAILS WHERE CITY = 'COIMBATORE' ORDER BY FIRSE_NAME ASC
SELECT * FROM CONTACT_DETAILS WHERE CITY = 'COIMBATORE' ORDER BY FIRSE_NAME DESC
SELECT * FROM CONTACT_DETAILS WHERE STATE = 'KARNATAKA' ORDER BY FIRSE_NAME

SELECT CITY, COUNT(CITY) AS TOTAL_COUNT FROM CONTACT_DETAILS GROUP BY CITY
SELECT CITY, COUNT(CITY) AS TOTAL_COUNT FROM CONTACT_DETAILS  WHERE CITY = 'COIMBATORE' GROUP BY CITY
SELECT STATE, COUNT(STATE) AS TOTAL_STATE_COUNT FROM CONTACT_DETAILS GROUP BY STATE

SELECT * FROM CONTACT_DETAILS WHERE CITY = 'COIMBATORE' ORDER BY FIRSE_NAME ASC

ALTER TABLE PHONE_NUMBER ADD CONSTRAINT FK_PN FOREIGN KEY (CONTACT_ID) REFERENCES CONTACT_DETAILS(CONTACT_ID) 
ALTER TABLE CONTACT_TYPE ADD CONSTRAINT FK_CT FOREIGN KEY (CONTACT_ID) REFERENCES CONTACT_DETAILS(CONTACT_ID)


SELECT  CONTACT_GROUP , COUNT(FIRSE_NAME) FROM CONTACT_DETAILS CD INNER JOIN CONTACT_TYPES CT ON CD.CONTACT_ID = CT.CONTACT_ID GROUP BY CT.CONTACT_GROUP

--SELECT COUNT(FIRSE_NAME) FROM CONTACT_DETAILS CD INNER JOIN CONTACT_TYPE CT ON CT.TYPE_ID = CA.TYPE_ID GROUP BY TYPE_NAME
--SELECT TYPE_NAME,CA.FIRST_NAME,PHONE_1 FROM CONTACT_TYPE CT INNER JOIN CONTACT_ADDRESS CA ON CT.TYPE_ID = CA.TYPE_ID INNER JOIN CONTACT_PHONE CP ON CA.CONTACT_ID = CP.CONTACT_ID
